<?php
require 'config/database.php';
require 'includes/functions.php';
$db = getDB();

$templates = [
  ['jenis_surat'=>'Surat Tugas Mengajar','nama_template'=>'Surat Tugas Mengajar Dosen','is_massal'=>0,
   'variabel'=>'{{NAMA_PENERIMA}},{{MATA_KULIAH}},{{SKS}},{{SEMESTER}},{{TAHUN_AKADEMIK}}',
   'isi'=>'<p>Dengan hormat,</p><p>Berdasarkan kebutuhan akademik Program Studi {{NAMA_PRODI}} Pascasarjana Universitas Nusa Putra, bersama ini kami menugaskan <strong>{{NAMA_PENERIMA}}</strong> untuk mengampu mata kuliah <strong>{{MATA_KULIAH}}</strong> ({{SKS}} SKS) pada Semester {{SEMESTER}} Tahun Akademik {{TAHUN_AKADEMIK}}.</p><p>Demikian surat tugas ini diberikan untuk dapat dilaksanakan dengan penuh tanggung jawab.</p>'],

  ['jenis_surat'=>'Surat Tugas Pembimbing','nama_template'=>'SK Dosen Pembimbing Tesis','is_massal'=>0,
   'variabel'=>'{{NAMA_PENERIMA}},{{NAMA_MAHASISWA}},{{NIM}},{{JUDUL_PENELITIAN}},{{TAHUN_AKADEMIK}}',
   'isi'=>'<p>Berdasarkan kebutuhan akademik dalam proses penyusunan Tesis mahasiswa Program Studi {{NAMA_PRODI}} Pascasarjana Universitas Nusa Putra, maka dengan ini menugaskan <strong>{{NAMA_PENERIMA}}</strong> sebagai <strong>Dosen Pembimbing Tesis</strong> bagi mahasiswa:</p><table style="width:100%;margin:12px 0"><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="width:35%"><strong>Nama</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_MAHASISWA}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>NIM</strong></td><td class="py-3 px-4 py-3 px-4">: {{NIM}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Program Studi</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_PRODI}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Judul Tesis</strong></td><td class="py-3 px-4 py-3 px-4">: <em>{{JUDUL_PENELITIAN}}</em></td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Tahun Akademik</strong></td><td class="py-3 px-4 py-3 px-4">: {{TAHUN_AKADEMIK}}</td></tr></table><p>Pembimbing diharapkan memberikan bimbingan secara berkala hingga mahasiswa tersebut menyelesaikan tesisnya.</p>'],

  ['jenis_surat'=>'Surat Keterangan Aktif','nama_template'=>'Surat Keterangan Aktif Kuliah','is_massal'=>0,
   'variabel'=>'{{NIM}},{{NAMA_MAHASISWA}},{{ANGKATAN}},{{KEPERLUAN}}',
   'isi'=>'<p>Yang bertanda tangan di bawah ini, Ketua Program Studi {{NAMA_PRODI}} Pascasarjana Universitas Nusa Putra, menerangkan bahwa:</p><table style="width:100%;margin:12px 0"><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="width:35%"><strong>Nama</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_MAHASISWA}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>NIM</strong></td><td class="py-3 px-4 py-3 px-4">: {{NIM}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Program Studi</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_PRODI}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Angkatan</strong></td><td class="py-3 px-4 py-3 px-4">: {{ANGKATAN}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Status</strong></td><td class="py-3 px-4 py-3 px-4">: Mahasiswa Aktif</td></tr></table><p>Mahasiswa tersebut benar terdaftar sebagai mahasiswa aktif pada Tahun Akademik <strong>{{TAHUN_AKADEMIK}}</strong>. Surat ini diterbitkan untuk keperluan: <strong>{{KEPERLUAN}}</strong>.</p><p>Demikian surat keterangan ini dibuat untuk dapat dipergunakan sebagaimana mestinya.</p>'],

  ['jenis_surat'=>'Surat Izin Penelitian','nama_template'=>'Surat Izin Penelitian Tesis','is_massal'=>0,
   'variabel'=>'{{NIM}},{{NAMA_MAHASISWA}},{{JUDUL_PENELITIAN}},{{LOKASI_PENELITIAN}},{{TANGGAL_MULAI}},{{TANGGAL_SELESAI}}',
   'isi'=>'<p>Dengan hormat,</p><p>Sehubungan dengan pelaksanaan penelitian Tesis, kami mengajukan permohonan izin penelitian atas nama mahasiswa:</p><table style="width:100%;margin:12px 0"><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="width:35%"><strong>Nama</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_MAHASISWA}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>NIM</strong></td><td class="py-3 px-4 py-3 px-4">: {{NIM}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Program Studi</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_PRODI}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Judul Penelitian</strong></td><td class="py-3 px-4 py-3 px-4">: {{JUDUL_PENELITIAN}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Lokasi</strong></td><td class="py-3 px-4 py-3 px-4">: {{LOKASI_PENELITIAN}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Periode</strong></td><td class="py-3 px-4 py-3 px-4">: {{TANGGAL_MULAI}} s.d. {{TANGGAL_SELESAI}}</td></tr></table><p>Atas perhatian dan kerjasamanya, kami ucapkan terima kasih.</p>'],

  ['jenis_surat'=>'Undangan Seminar Proposal','nama_template'=>'Undangan Seminar Proposal Tesis','is_massal'=>1,
   'variabel'=>'{{NAMA_PRESENTER}},{{NIM}},{{JUDUL_TESIS}},{{TANGGAL_KEGIATAN}},{{WAKTU}},{{TEMPAT}}',
   'isi'=>'<p>Dengan hormat,</p><p>Dalam rangka Seminar Proposal Tesis Program Studi {{NAMA_PRODI}}, kami mengundang Bapak/Ibu untuk hadir pada:</p><table style="width:100%;border-collapse:collapse;margin:12px 0"><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="width:35%;padding:5px 0"><strong>Jenis Kegiatan</strong></td><td class="py-3 px-4 py-3 px-4">: Seminar Proposal Tesis</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Presenter</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_PRESENTER}} ({{NIM}})</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Judul</strong></td><td class="py-3 px-4 py-3 px-4">: <em>{{JUDUL_TESIS}}</em></td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Hari/Tanggal</strong></td><td class="py-3 px-4 py-3 px-4">: {{TANGGAL_KEGIATAN}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Pukul</strong></td><td class="py-3 px-4 py-3 px-4">: {{WAKTU}} WIB</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Tempat</strong></td><td class="py-3 px-4 py-3 px-4">: {{TEMPAT}}</td></tr></table><p>Kehadiran Bapak/Ibu sangat kami harapkan. Atas perhatian dan kehadirannya, kami ucapkan terima kasih.</p>'],

  ['jenis_surat'=>'Undangan Sidang Tesis','nama_template'=>'Undangan Sidang Tesis (Tim Penguji)','is_massal'=>1,
   'variabel'=>'{{NAMA_PRESENTER}},{{NIM}},{{JUDUL_TESIS}},{{TANGGAL_KEGIATAN}},{{WAKTU}},{{TEMPAT}}',
   'isi'=>'<p>Dengan hormat,</p><p>Dalam rangka Sidang Tesis Program Studi {{NAMA_PRODI}} Pascasarjana Universitas Nusa Putra, kami mengundang Bapak/Ibu Dosen sebagai Tim Penguji pada:</p><table style="width:100%;border-collapse:collapse;margin:12px 0"><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="width:35%;padding:5px 0"><strong>Jenis Ujian</strong></td><td class="py-3 px-4 py-3 px-4">: Sidang Tesis</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Nama Mahasiswa</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_PRESENTER}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>NIM</strong></td><td class="py-3 px-4 py-3 px-4">: {{NIM}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Judul Tesis</strong></td><td class="py-3 px-4 py-3 px-4">: <em>{{JUDUL_TESIS}}</em></td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Hari/Tanggal</strong></td><td class="py-3 px-4 py-3 px-4">: {{TANGGAL_KEGIATAN}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Pukul</strong></td><td class="py-3 px-4 py-3 px-4">: {{WAKTU}} WIB</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Tempat</strong></td><td class="py-3 px-4 py-3 px-4">: {{TEMPAT}}</td></tr></table><p>Kehadiran Bapak/Ibu sebagai penguji sangat kami harapkan. Mohon konfirmasi kehadiran kepada sekretariat selambat-lambatnya 2 hari sebelum pelaksanaan.</p><p>Atas perhatian dan kesediaan Bapak/Ibu, kami ucapkan terima kasih.</p>'],

  ['jenis_surat'=>'SK Kelulusan','nama_template'=>'SK Kelulusan / Yudisium','is_massal'=>0,
   'variabel'=>'{{NIM}},{{NAMA_MAHASISWA}},{{IPK}},{{TANGGAL_YUDISIUM}},{{PREDIKAT}}',
   'isi'=>'<p>Berdasarkan hasil Sidang Yudisium Program Studi {{NAMA_PRODI}} Pascasarjana Universitas Nusa Putra tanggal {{TANGGAL_YUDISIUM}}, maka:</p><table style="width:100%;margin:12px 0"><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="width:35%"><strong>Nama</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_MAHASISWA}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>NIM</strong></td><td class="py-3 px-4 py-3 px-4">: {{NIM}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Program Studi</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_PRODI}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>IPK</strong></td><td class="py-3 px-4 py-3 px-4">: {{IPK}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Predikat</strong></td><td class="py-3 px-4 py-3 px-4">: <strong>{{PREDIKAT}}</strong></td></tr></table><p>Dinyatakan <strong>LULUS</strong> dan berhak memperoleh gelar sesuai Program Studi yang ditempuh.</p>'],

  ['jenis_surat'=>'Surat Rekomendasi','nama_template'=>'Surat Rekomendasi Mahasiswa','is_massal'=>0,
   'variabel'=>'{{NIM}},{{NAMA_MAHASISWA}},{{TUJUAN_REKOMENDASI}},{{PRESTASI}}',
   'isi'=>'<p>Yang bertanda tangan di bawah ini, Ketua Program Studi {{NAMA_PRODI}} Pascasarjana Universitas Nusa Putra, memberikan rekomendasi kepada:</p><table style="width:100%;margin:12px 0"><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="width:35%"><strong>Nama</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_MAHASISWA}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>NIM</strong></td><td class="py-3 px-4 py-3 px-4">: {{NIM}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Program Studi</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_PRODI}}</td></tr></table><p>{{PRESTASI}}</p><p>Kami merekomendasikan yang bersangkutan untuk: <strong>{{TUJUAN_REKOMENDASI}}</strong>.</p><p>Demikian surat rekomendasi ini dibuat untuk dapat digunakan sebagaimana mestinya.</p>'],

  ['jenis_surat'=>'Surat Pengantar Ijazah','nama_template'=>'Surat Pengantar Pengambilan Ijazah','is_massal'=>0,
   'variabel'=>'{{NIM}},{{NAMA_MAHASISWA}},{{NO_IJAZAH}}',
   'isi'=>'<p>Dengan hormat,</p><p>Bersama ini kami sampaikan bahwa mahasiswa berikut telah menyelesaikan studi dan berhak mengambil ijazah:</p><table style="width:100%;margin:12px 0"><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="width:35%"><strong>Nama</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_MAHASISWA}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>NIM</strong></td><td class="py-3 px-4 py-3 px-4">: {{NIM}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Program Studi</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_PRODI}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Nomor Ijazah</strong></td><td class="py-3 px-4 py-3 px-4">: {{NO_IJAZAH}}</td></tr></table><p>Mohon ijazah dapat diserahkan kepada yang bersangkutan dengan menunjukkan surat ini dan kartu identitas.</p>'],

  ['jenis_surat'=>'Surat Pemberitahuan','nama_template'=>'Surat Pemberitahuan Umum (Massal)','is_massal'=>1,
   'variabel'=>'{{PERIHAL}},{{ISI_PEMBERITAHUAN}},{{TANGGAL_PELAKSANAAN}}',
   'isi'=>'<p>Dengan hormat,</p><p>Bersama ini kami sampaikan pemberitahuan mengenai: <strong>{{PERIHAL}}</strong></p><p>{{ISI_PEMBERITAHUAN}}</p><p>Kegiatan akan dilaksanakan pada tanggal <strong>{{TANGGAL_PELAKSANAAN}}</strong>.</p><p>Atas perhatian dan kerjasamanya, kami ucapkan terima kasih.</p>'],

  ['jenis_surat'=>'Surat Permohonan','nama_template'=>'Surat Permohonan ke Instansi Luar','is_massal'=>0,
   'variabel'=>'{{NAMA_INSTANSI}},{{ALAMAT_INSTANSI}},{{ISI_PERMOHONAN}}',
   'isi'=>'<p>Dengan hormat,</p><p>Program Studi {{NAMA_PRODI}} Pascasarjana Universitas Nusa Putra mengajukan permohonan kepada <strong>{{NAMA_INSTANSI}}</strong> yang beralamat di {{ALAMAT_INSTANSI}}.</p><p>Adapun permohonan kami: {{ISI_PERMOHONAN}}</p><p>Besar harapan kami permohonan ini dapat dikabulkan. Atas perhatian dan kerjasamanya, kami ucapkan terima kasih.</p>'],

  ['jenis_surat'=>'Surat Perpanjangan Studi','nama_template'=>'Surat Permohonan Perpanjangan Studi','is_massal'=>0,
   'variabel'=>'{{NAMA_MAHASISWA}},{{NIM}},{{ANGKATAN}},{{KEPERLUAN}},{{TANGGAL_SELESAI}}',
   'isi'=>'<p>Dengan hormat,</p><p>Sehubungan dengan belum selesainya penyusunan tesis, kami mengajukan permohonan perpanjangan masa studi bagi mahasiswa:</p><table style="width:100%;margin:12px 0"><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="width:35%"><strong>Nama</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_MAHASISWA}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>NIM</strong></td><td class="py-3 px-4 py-3 px-4">: {{NIM}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Program Studi</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_PRODI}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Angkatan</strong></td><td class="py-3 px-4 py-3 px-4">: {{ANGKATAN}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Alasan</strong></td><td class="py-3 px-4 py-3 px-4">: {{KEPERLUAN}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Target Selesai</strong></td><td class="py-3 px-4 py-3 px-4">: {{TANGGAL_SELESAI}}</td></tr></table><p>Mahasiswa berkomitmen menyelesaikan studi sesuai target. Atas perhatian dan kebijaksanaan Bapak/Ibu, kami ucapkan terima kasih.</p>'],

  ['jenis_surat'=>'Surat Cuti Akademik','nama_template'=>'Surat Permohonan Cuti Akademik','is_massal'=>0,
   'variabel'=>'{{NAMA_MAHASISWA}},{{NIM}},{{SEMESTER}},{{KEPERLUAN}},{{TANGGAL_MULAI}},{{TANGGAL_SELESAI}}',
   'isi'=>'<p>Dengan hormat,</p><p>Kami menerangkan bahwa mahasiswa berikut mengajukan permohonan cuti akademik:</p><table style="width:100%;margin:12px 0"><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="width:35%"><strong>Nama</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_MAHASISWA}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>NIM</strong></td><td class="py-3 px-4 py-3 px-4">: {{NIM}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Program Studi</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_PRODI}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Semester</strong></td><td class="py-3 px-4 py-3 px-4">: {{SEMESTER}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Alasan</strong></td><td class="py-3 px-4 py-3 px-4">: {{KEPERLUAN}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Periode Cuti</strong></td><td class="py-3 px-4 py-3 px-4">: {{TANGGAL_MULAI}} s.d. {{TANGGAL_SELESAI}}</td></tr></table><p>Selama masa cuti, mahasiswa tidak diperkenankan mengikuti kegiatan akademik. Demikian untuk dapat digunakan sebagaimana mestinya.</p>'],

  ['jenis_surat'=>'Surat Bebas Perpustakaan','nama_template'=>'Surat Keterangan Bebas Perpustakaan','is_massal'=>0,
   'variabel'=>'{{NAMA_MAHASISWA}},{{NIM}},{{KEPERLUAN}}',
   'isi'=>'<p>Yang bertanda tangan di bawah ini, Ketua Program Studi {{NAMA_PRODI}} Pascasarjana Universitas Nusa Putra, menerangkan bahwa:</p><table style="width:100%;margin:12px 0"><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="width:35%"><strong>Nama</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_MAHASISWA}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>NIM</strong></td><td class="py-3 px-4 py-3 px-4">: {{NIM}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4 py-3 px-4"><strong>Program Studi</strong></td><td class="py-3 px-4 py-3 px-4">: {{NAMA_PRODI}}</td></tr></table><p>Mahasiswa tersebut dinyatakan <strong>BEBAS</strong> dari pinjaman dan tanggungan perpustakaan Universitas Nusa Putra. Surat ini diberikan untuk keperluan: <strong>{{KEPERLUAN}}</strong>.</p>'],

  ['jenis_surat'=>'Surat Undangan Rapat','nama_template'=>'Undangan Rapat Program Studi (Massal)','is_massal'=>1,
   'variabel'=>'{{JENIS_KEGIATAN}},{{TANGGAL_KEGIATAN}},{{WAKTU}},{{TEMPAT}},{{ISI_PEMBERITAHUAN}}',
   'isi'=>'<p>Dengan hormat,</p><p>Mengharap kehadiran Bapak/Ibu dalam kegiatan:</p><table style="width:100%;border-collapse:collapse;margin:12px 0"><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="width:35%;padding:5px 0"><strong>Acara</strong></td><td class="py-3 px-4 py-3 px-4">: {{JENIS_KEGIATAN}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Hari/Tanggal</strong></td><td class="py-3 px-4 py-3 px-4">: {{TANGGAL_KEGIATAN}}</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Pukul</strong></td><td class="py-3 px-4 py-3 px-4">: {{WAKTU}} WIB</td></tr><tr class="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition"><td class="py-3 px-4" style="padding:5px 0"><strong>Tempat</strong></td><td class="py-3 px-4 py-3 px-4">: {{TEMPAT}}</td></tr></table><p>Agenda: {{ISI_PEMBERITAHUAN}}</p><p>Kehadiran Bapak/Ibu tepat waktu sangat kami harapkan. Atas perhatian dan kehadirannya, kami ucapkan terima kasih.</p>'],

  ['jenis_surat'=>'Berita Acara','nama_template'=>'Berita Acara Kegiatan','is_massal'=>0,
   'variabel'=>'{{JENIS_KEGIATAN}},{{TANGGAL_KEGIATAN}},{{PESERTA}},{{HASIL_KEGIATAN}}',
   'isi'=>'<p style="text-align:center"><strong>BERITA ACARA {{JENIS_KEGIATAN}}</strong></p><p>Pada hari ini, {{TANGGAL_KEGIATAN}}, telah dilaksanakan <strong>{{JENIS_KEGIATAN}}</strong> dengan peserta: {{PESERTA}}.</p><p><strong>Hasil Kegiatan:</strong></p><p>{{HASIL_KEGIATAN}}</p><p>Demikian berita acara ini dibuat dengan sebenarnya untuk dapat dipergunakan sebagaimana mestinya.</p>'],
];

$db->exec("DELETE FROM template_surat");
$stmt = $db->prepare("INSERT INTO template_surat (jenis_surat, nama_template, isi_template, variabel_tersedia, is_massal) VALUES (?,?,?,?,?)");
foreach ($templates as $t) {
    $stmt->execute([$t['jenis_surat'], $t['nama_template'], $t['isi'], $t['variabel'], $t['is_massal']]);
}
echo "<div style='font-family:monospace;background:var(--color-bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl shadow-sm);color:#e2e8f0;padding:20px;border-radius:12px'>";
echo "<h2 style='color:#22c55e'>✅ " . count($templates) . " Template Surat Berhasil Dibuat!</h2>";
foreach ($templates as $t) {
    echo "<p>• " . $t['nama_template'] . " " . ($t['is_massal'] ? "<span style='color:#f59e0b'>[Massal]</span>" : "") . "</p>";
}
echo "<br><a href='pages/surat_keluaran' style='background:var(--color-primary);color:#fff;padding:10px 20px;border-radius:8px;text-decoration:none;font-weight:bold'>→ Lihat Surat Keluaran</a></div>";
?>
